### ISSUE TITLE
Can't use server.subscribe for messages via sidecar

### ISSUE THREAD

**Issue by bram96** [micro/micro#67] opened 2016-09-05 10:24 UTC
I am using sidecar for asynchronous communication with a python service.

I tried to receive the messages with server.subscribe(<subscriber>) but I couldn't get that working because sidecar does not set the Header of the message and go-micro checks for a valid content type (https://github.com/micro/go-micro/blob/master/server/subscriber.go#L166). 

When I use broker.subscribe it is working, I use this as workaround for the content-type issue. The server.subscribe option is much nicer because go-micro will unmarshall the protobuf and call the handler for me.

It would be nice when I can use server.subscribe with sidecar.

**Comment by asim** [comment] 2016-09-06 08:23
Easiest fix would probably be to have the sidecar accept a broker.Message rather than filling in the body of a broker.Message with whatever's passed in. It's a breaking change though so it affects anyone already using the sidecar. I'll have to give it some thought.

**Comment by bkleef** [comment] 2016-10-07 12:23
@asim any thoughts on this?

**Comment by asim** [comment] 2016-10-07 12:55
The issue is because of this https://github.com/micro/micro/blob/master/internal/handler/broker.go#L56. I'm open to suggestions on a fix, otherwise I'm not touching it for the moment.

**Comment by asim** [comment] 2016-10-07 13:01
An easy solution would perhaps be to take Content-Type from the initial request and use that as the basis for any messages published.

**Comment by asim** [comment] 2016-10-07 13:18
https://github.com/micro/micro/pull/70

**Comment by asim** [comment] 2016-10-14 13:45
Merged PR.

**Closed by asim** 2016-10-14 13:45 UTC
