### ISSUE TITLE
Can't run service from template

### ISSUE THREAD

**Issue by BaltsevichDanil** [micro/micro#2075] opened 2024-07-13 16:49 UTC
**Describe the bug**
When: I was trying create service from CLI and trying to start it by `micro run  .`
Problem: I was getting this error in console 
```
Exit status 1: go: userservice/proto imports
        go-micro.dev/v4/api: no required module provides package go-micro.dev/v4/api; to add it:
        go get go-micro.dev/v4/api
go: userservice/proto imports
        go-micro.dev/v4/client: no required module provides package go-micro.dev/v4/client; to add it:
        go get go-micro.dev/v4/client
go: userservice/proto imports
        go-micro.dev/v4/server: no required module provides package go-micro.dev/v4/server; to add it:
        go get go-micro.dev/v4/server
```

**To Reproduce**
1. Install micro - `go install micro.dev/v4/cmd/micro@master`
2. Create service - `micro new usersservice`
3. Run this commands - `cd userservice; go mod tidy; make proto; micro run .`
```
  Exit status 1: go: userservice/proto imports
          go-micro.dev/v4/api: no required module provides package go-micro.dev/v4/api; to add it:
          go get go-micro.dev/v4/api
  go: userservice/proto imports
          go-micro.dev/v4/client: no required module provides package go-micro.dev/v4/client; to add it:
          go get go-micro.dev/v4/client
  go: userservice/proto imports
          go-micro.dev/v4/server: no required module provides package go-micro.dev/v4/server; to add it:
          go get go-micro.dev/v4/server
```

**Expected behavior**
Micro service starts.

**Additional info**
If run `go mod tidy` one more time after `make proto`, I get this error - 
```
go: finding module for package go-micro.dev/v4/server
go: finding module for package go-micro.dev/v4/api
go: finding module for package go-micro.dev/v4/client
go: found go-micro.dev/v4/api in go-micro.dev/v4/api v1.18.0
go: found go-micro.dev/v4/client in go-micro.dev/v4/client v1.18.0
go: found go-micro.dev/v4/server in go-micro.dev/v4/server v1.18.0
go: userservice/proto imports
        go-micro.dev/v4/api: go-micro.dev/v4/api@v1.18.0: parsing go.mod:
        module declares its path as: github.com/micro/go-micro
                but was required as: go-micro.dev/v4/api

```
**Desktop (please complete the following information):**
 - OS: mac os

**Comment by asim** [comment] 2024-07-13 17:16
I am assuming you are using the protoc-gen-micro that's in go-micro. You will want `go get micro.dev/v4/cmd/protoc-gen-micro@master`. Currently there's still a split between the projects that needs to be merged.

**Comment by BaltsevichDanil** [comment] 2024-07-13 18:30
I tried running `go get micro.dev/v4/cmd/protoc-gen-micro@master`, but it didn't help me. Are there any actions I can take right now to fix this issue? Or do I need to wait until the split between projects will be merged?

**Comment by asim** [comment] 2024-07-13 21:00
```go install micro.dev/v4/cmd/protoc-gen-micro@master```

If you do this and re-run `make proto` then you should see the generated code contains imports for micro.dev, not go-micro.dev. The issue is that your generated protos reference go-micro, this can only happen if you are using the protoc-gen-micro binary from go-micro. So I'd advice you to delete `protoc-gen-micro` and then reinstall it as mentioned above.

**Comment by BaltsevichDanil** [comment] 2024-07-13 21:58
> `go install micro.dev/v4/cmd/protoc-gen-micro@master`

It helped, thanks!

**Comment by asim** [comment] 2024-07-13 22:30
Ok great glad to hear it. Closing the issue

**Closed by asim** 2024-07-13 22:30 UTC
