### ISSUE TITLE
micro api can't close socket 

### ISSUE THREAD

**Issue by laoqiu** [micro/micro#170] opened 2018-05-24 09:18 UTC
启动micro api后, 使用netstat -net查看api连接数是正常的(我运行在docker上)
当postman在8080端口上访问一次，连接数就会增加3-5个，而且不会回收，一直增加，直到无法分配更多的端口
看下面netstat -net查看到的信息
tcp        0      0 172.28.0.4:35950        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:34324        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:38144        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:44192        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:34684        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:43330        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:34966        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:33154        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:33006        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:47770        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:43808        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:32914        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:41100        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:45290        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:40262        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:38242        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:44196        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:46308        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:34336        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:33102        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:39210        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:45166        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:34372        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:46410        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:44488        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:40160        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:34450        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:41196        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:45730        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:35858        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:38274        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:33274        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:37314        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:45936        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:33712        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:60696        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:44788        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:45250        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:60930        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:33128        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:37256        172.28.0.2:8500         ESTABLISHED
tcp        0      0 172.28.0.4:35338        172.28.0.2:8500         ESTABLISHED

过不了多长时间，api就会因为端口使用光，而报错，最终退出consul检查，无法提供服务

我测试过，不开micro api，而使用micro web来调用，是正常的。

对不起，无法使用英文表达以上内容

**Comment by laoqiu** [comment] 2018-05-24 09:20
This is my docker-compose config file:
consul-bootstrap:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap -ui -client 0.0.0.0"
    networks:
      default:

  api: &api
    image: microhq/micro:latest
    networks:
      - default
    depends_on:
      - consul-bootstrap
    ports:
      - "8080:8080"
    command: --registry_address=consul-bootstrap:8500 --enable_stats --register_interval=5 --register_ttl=10 api --namespace=cn.xxx.api

**Comment by asim** [comment] 2018-05-24 09:38
Is there an actual issue? Some sort of error? I believe this is standard behaviour. Micro makes use of the consul api client which uses net/http. This may be creating new connections, but I'm not completely sure.

**Comment by asim** [comment] 2018-05-24 09:40
How many services are you serving behind the micro api? Another thought is that when a new watcher is created to watch a service, the consul client api may be creating a new connection to consul to maintain a watch.

**Comment by laoqiu** [comment] 2018-05-24 10:38
i know the watch event, and it not happen on my mac.
i am still testing, closed all services, left one to test, i got many connection when i uses http fetch, every time.

i have no idea, when micro api let me see "Cannot assign requested address"

**Comment by laoqiu** [comment] 2018-05-24 10:42
The last services, I left that, just return a message, no client, no other code.

**Comment by asim** [comment] 2018-05-24 10:47
Hmm, yea I can see this leak even in local testing. Not exactly sure why it's creating so many connections. Feel free to help me debug by looking at the consul code here https://github.com/micro/go-micro/tree/master/registry

**Comment by laoqiu** [comment] 2018-05-24 10:56
Same code and docker config/version, that not happen on my mac.
so, how to fix this?

**Comment by laoqiu** [comment] 2018-05-24 11:07
everything is right when i use micro web to send data from 8082 port

**Comment by asim** [comment] 2018-05-24 11:13
Micro web is using different code. I've found the issue and committed a fix. Please update your deps. The issue is related to creating new options with create a new router and with it a new rcache instance on every request. I've stopped doing this and now the connections do not leak. Please let me know if the fix works for you.

https://github.com/micro/go-api/commit/b77313d0bbce97b6a1b37169b58df38e4a78df6a.

**Comment by laoqiu** [comment] 2018-05-25 02:02
Fixed, thx, i have nevery think docker images latest tag not real latest.
Thank you for your help!

**Closed** 2018-05-25 05:32 UTC
