### ISSUE TITLE
How to use micro upload file

### ISSUE THREAD

**Issue by scholar-ink** [micro/micro#243] opened 2019-03-09 07:02 UTC
```
micro api --handler=api
error:   proto: field \"go.micro.api.Request.Body\" contains invalid UTF-8
```
```
micro api -handler=http
error:   Unsupported Content-Type: multipart/form-data
```

**Comment by scholar-ink** [comment] 2019-03-09 07:03
The old version was right to use micro api --handler=api

**Comment by prksu** [comment] 2019-03-09 07:14
Duplicate of https://github.com/micro/go-api/issues/16

**Closed** 2019-03-09 09:10 UTC
